In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split 
import time
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.feature_selection import f_regression
from sklearn.feature_selection import RFE
from sklearn.linear_model import LogisticRegression
import pickle
import matplotlib.pyplot as plt
import warnings
warnings.filterwarnings("ignore")

In [2]:
def selectkbest(indep_X,dep_Y,n):
        test = SelectKBest(score_func=f_regression, k=n)
        fit1= test.fit(indep_X,dep_Y)
        # summarize scores       
        selectk_features = fit1.transform(indep_X)
        return selectk_features
    
def split_scalar(indep_X,dep_Y):
        X_train, X_test, y_train, y_test = train_test_split(indep_X, dep_Y, test_size = 0.25, random_state = 0)
        sc = StandardScaler()
        X_train = sc.fit_transform(X_train)
        X_test = sc.transform(X_test)    
        return X_train, X_test, y_train, y_test
    
def r2_prediction(regressor,X_test,y_test):
     y_pred = regressor.predict(X_test)
     from sklearn.metrics import r2_score
     r2=r2_score(y_test,y_pred)
     return r2
 
def Linear(X_train,y_train,X_test):       
        
        from sklearn.linear_model import LinearRegression
        regressor = LinearRegression()
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2   
    
def svm_linear(X_train,y_train,X_test):
                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'linear')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2  
    
def svm_NL(X_train,y_train,X_test):
                
        from sklearn.svm import SVR
        regressor = SVR(kernel = 'rbf')
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2  
     

def Decision(X_train,y_train,X_test):
        
        from sklearn.tree import DecisionTreeRegressor
        regressor = DecisionTreeRegressor(random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2  
     

def random(X_train,y_train,X_test):       
        
        from sklearn.ensemble import RandomForestRegressor
        regressor = RandomForestRegressor(n_estimators = 10, random_state = 0)
        regressor.fit(X_train, y_train)
        r2=r2_prediction(regressor,X_test,y_test)
        return  r2

In [3]:
def selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf): 
    
    dataframe=pd.DataFrame(index=['f_regression'],columns=['Linear','SVMl','SVMnl','Decision','Random'
                                                                                     ])

    for number,idex in enumerate(dataframe.index):
        
        dataframe['Linear'][idex]=acclin[number]       
        dataframe['SVMl'][idex]=accsvml[number]
        dataframe['SVMnl'][idex]=accsvmnl[number]
        dataframe['Decision'][idex]=accdes[number]
        dataframe['Random'][idex]=accrf[number]
    return dataframe

In [4]:
dataset=pd.read_csv("Walmart dataset.csv",sep= ';', index_col=None)

In [5]:
dataset

,invoice_id,branch,city,customer_type,gender,product_line,unit_price,quantity,vat,total,dtme,tme,payment_method,cogs,gross_margin_pct,gross_income,rating,time_of_day,day_name,month_name
0,750-67-8428,A,Yangon,Member,Female,Health and beauty,74.69,7,26.1415,548.9715,2019-01-05 00:00:00,13:08:00,Ewallet,522.83,4.7619,26.1415,9.1,afternoon,Saturday,January
1,226-31-3081,C,Naypyitaw,Normal,Female,Electronic accessories,15.28,5,3.8200,80.2200,2019-03-08 00:00:00,10:29:00,Cash,76.40,4.7619,3.8200,9.6,morning,Friday,March
2,631-41-3108,A,Yangon,Normal,Male,Home and lifestyle,46.33,7,16.2155,340.5255,2019-03-03 00:00:00,13:23:00,Credit card,324.31,4.7619,16.2155,7.4,afternoon,Sunday,March
3,123-19-1176,A,Yangon,Member,Male,Health and beauty,58.22,8,23.2880,489.0480,2019-01-27 00:00:00,20:33:00,Ewallet,465.76,4.7619,23.2880,8.4,evening,Sunday,January
4,373-73-7910,A,Yangon,Normal,Male,Sports and travel,86.31,7,30.2085,634.3785,2019-02-08 00:00:00,10:37:00,Ewallet,604.17,4.7619,30.2085,5.3,morning,Friday,February
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,233-67-5758,C,Naypyitaw,Normal,Male,Health and beauty,40.35,1,2.0175,42.3675,2019-01-29 00:00:00,13:46:00,Ewallet,40.35,4.7619,2.0175,6.2,afternoon,Tuesday,January
996,303-96-2227,B,Mandalay,Normal,Female,Home and lifestyle,97.38,10,48.6900,1022.4900,2019-03-02 00:00:00,17:16:00,Ewallet,973.80,4.7619,48.6900,4.4,evening,Saturday,March
997,727-02-1313,A,Yangon,Member,Male,Food and beverages,31.84,1,1.5920,33.4320,2019-02-09 00:00:00,13:22:00,Cash,31.84,4.7619,1.5920,7.7,afternoon,Saturday,February
998,347-56-2442,A,Yangon,Normal,Male,Home and lifestyle,65.82,1,3.2910,69.1110,2019-02-22 00:00:00,15:33:00,Cash,65.82,4.7619,3.2910,4.1,afternoon,Friday,February
999,849-09-3807,A,Yangon,Member,Female,Fashion accessories,88.34,7,30.9190,649.2990,2019-02-18 00:00:00,13:28:00,Cash,618.38,4.7619,30.9190,6.6,afternoon,Monday,February

In [6]:
df1=dataset.drop(columns=['invoice_id','dtme','tme'],axis=1)

In [7]:
df2=df1

df2 = pd.get_dummies(df2, drop_first=True)

In [8]:
df2

,unit_price,quantity,vat,total,cogs,gross_margin_pct,gross_income,rating,branch_B,branch_C,...,time_of_day_evening,time_of_day_morning,day_name_Monday,day_name_Saturday,day_name_Sunday,day_name_Thursday,day_name_Tuesday,day_name_Wednesday,month_name_January,month_name_March
0,74.69,7,26.1415,548.9715,522.83,4.7619,26.1415,9.1,False,False,...,False,False,False,True,False,False,False,False,True,False
1,15.28,5,3.8200,80.2200,76.40,4.7619,3.8200,9.6,False,True,...,False,True,False,False,False,False,False,False,False,True
2,46.33,7,16.2155,340.5255,324.31,4.7619,16.2155,7.4,False,False,...,False,False,False,False,True,False,False,False,False,True
3,58.22,8,23.2880,489.0480,465.76,4.7619,23.2880,8.4,False,False,...,True,False,False,False,True,False,False,False,True,False
4,86.31,7,30.2085,634.3785,604.17,4.7619,30.2085,5.3,False,False,...,False,True,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
995,40.35,1,2.0175,42.3675,40.35,4.7619,2.0175,6.2,False,True,...,False,False,False,False,False,False,True,False,True,False
996,97.38,10,48.6900,1022.4900,973.80,4.7619,48.6900,4.4,True,False,...,True,False,False,True,False,False,False,False,False,True
997,31.84,1,1.5920,33.4320,31.84,4.7619,1.5920,7.7,False,False,...,False,False,False,True,False,False,False,False,False,False
998,65.82,1,3.2910,69.1110,65.82,4.7619,3.2910,4.1,False,False,...,False,False,False,False,False,False,False,False,False,False
999,88.34,7,30.9190,649.2990,618.38,4.7619,30.9190,6.6,False,False,...,False,False,True,False,False,False,False,False,False,False

In [9]:
df2.columns

Index(['unit_price', 'quantity', 'vat', 'total', 'cogs', 'gross_margin_pct',
       'gross_income', 'rating', 'branch_B', 'branch_C', 'city_Naypyitaw',
       'city_Yangon', 'customer_type_Normal', 'gender_Male',
       'product_line_Fashion accessories', 'product_line_Food and beverages',
       'product_line_Health and beauty', 'product_line_Home and lifestyle',
       'product_line_Sports and travel', 'payment_method_Credit card',
       'payment_method_Ewallet', 'time_of_day_evening', 'time_of_day_morning',
       'day_name_Monday', 'day_name_Saturday', 'day_name_Sunday',
       'day_name_Thursday', 'day_name_Tuesday', 'day_name_Wednesday',
       'month_name_January', 'month_name_March'],
      dtype='object')

In [10]:
indep_X=df2.drop('total', axis=1)

dep_Y=df2['total'].astype(float)

In [17]:
kbest=selectkbest(indep_X,dep_Y,4)      

acclin=[]
accsvml=[]
accsvmnl=[]
accdes=[]
accrf=[]

In [18]:
X_train, X_test, y_train, y_test=split_scalar(kbest,dep_Y)  
for i in kbest:   
    r2_lin=Linear(X_train,y_train,X_test)
    acclin.append(r2_lin)
    
    r2_sl=svm_linear(X_train,y_train,X_test)    
    accsvml.append(r2_sl)
    
    r2_NL=svm_NL(X_train,y_train,X_test)
    accsvmnl.append(r2_NL)
    
    r2_d=Decision(X_train,y_train,X_test)
    accdes.append(r2_d)
    
    r2_r=random(X_train,y_train,X_test)
    accrf.append(r2_r)
    
    
result=selectk_regression(acclin,accsvml,accsvmnl,accdes,accrf)

In [13]:
result
#6

          Linear SVMl     SVMnl  Decision    Random
ChiSquare    1.0  1.0  0.559033  0.999947  0.999974

In [16]:
result 
#5

          Linear SVMl     SVMnl  Decision    Random
ChiSquare    1.0  1.0  0.632066  0.999973  0.999973

In [19]:
result 
#4

          Linear SVMl     SVMnl Decision    Random
ChiSquare    1.0  1.0  0.663345  0.99998  0.999977

In [23]:
kbest.tolist()

[[7.0, 26.1415, 522.83, 26.1415],
 [5.0, 3.82, 76.4, 3.82],
 [7.0, 16.2155, 324.31, 16.2155],
 [8.0, 23.288, 465.76, 23.288],
 [7.0, 30.2085, 604.17, 30.2085],
 [7.0, 29.8865, 597.73, 29.8865],
 [6.0, 20.652, 413.04, 20.652],
 [10.0, 36.78, 735.6, 36.78],
 [2.0, 3.626, 72.52, 3.626],
 [3.0, 8.226, 164.52, 8.226],
 [4.0, 2.896, 57.92, 2.896],
 [4.0, 5.102, 102.04, 5.102],
 [5.0, 11.7375, 234.75, 11.7375],
 [10.0, 21.595, 431.9, 21.595],
 [10.0, 35.69, 713.8, 35.69],
 [6.0, 28.116, 562.32, 28.116],
 [7.0, 24.1255, 482.51, 24.1255],
 [6.0, 21.783, 435.66, 21.783],
 [3.0, 8.2005, 164.01, 8.2005],
 [2.0, 4.03, 80.6, 4.03],
 [5.0, 21.51, 430.2, 21.51],
 [3.0, 13.197, 263.94, 13.197],
 [2.0, 3.32, 66.4, 3.32],
 [5.0, 8.64, 172.8, 8.64],
 [3.0, 13.2945, 265.89, 13.2945],
 [8.0, 21.036, 420.72, 21.036],
 [1.0, 1.676, 33.52, 1.676],
 [2.0, 8.767, 175.34, 8.767],
 [5.0, 22.09, 441.8, 22.09],
 [9.0, 11.2005, 224.01, 11.2005],
 [5.0, 23.5325, 470.65, 23.5325],
 [9.0, 35.1315, 702.63, 35.1315],
 [8.0, 33.512, 670.24, 33.512],
 [2.0, 9.658, 193.16, 9.658],
 [4.0, 19.884, 397.68, 19.884],
 [1.0, 3.406, 68.12, 3.406],
 [5.0, 15.655, 313.1, 15.655],
 [9.0, 27.396, 547.92, 27.396],
 [8.0, 21.968, 439.36, 21.968],
 [8.0, 12.048, 240.96, 12.048],
 [1.0, 4.336, 86.72, 4.336],
 [2.0, 5.611, 112.22, 5.611],
 [6.0, 20.736, 414.72, 20.736],
 [8.0, 39.48, 789.6, 39.48],
 [2.0, 1.537, 30.74, 1.537],
 [4.0, 18.792, 375.84, 18.792],
 [9.0, 25.5105, 510.21, 25.5105],
 [9.0, 9.0045, 180.09, 9.0045],
 [6.0, 5.679, 113.58, 5.679],
 [10.0, 41.315, 826.3, 41.315],
 [7.0, 31.99, 639.8, 31.99],
 [5.0, 11.1475, 222.95, 11.1475],
 [4.0, 3.574, 71.48, 3.574],
 [1.0, 0.7715, 15.43, 0.7715],
 [2.0, 1.616, 32.32, 1.616],
 [8.0, 34.392, 687.84, 34.392],
 [2.0, 4.434, 88.68, 4.434],
 [8.0, 35.84, 716.8, 35.84],
 [10.0, 36.175, 723.5, 36.175],
 [6.0, 9.183, 183.66, 9.183],
 [3.0, 3.711, 74.22, 3.711],
 [6.0, 16.719, 334.38, 16.719],
 [9.0, 24.7815, 495.63, 24.7815],
 [10.0, 7.905, 158.1, 7.905],
 [4.0, 15.148, 302.96, 15.148],
 [10.0, 7.935, 158.7, 7.935],
 [2.0, 3.347, 66.94, 3.347],
 [6.0, 29.283, 585.66, 29.283],
 [10.0, 39.385, 787.7, 39.385],
 [1.0, 0.9165, 18.33, 0.9165],
 [10.0, 44.74, 894.8, 44.74],
 [10.0, 31.06, 621.2, 31.06],
 [3.0, 7.278, 145.56, 7.278],
 [6.0, 22.773, 455.46, 22.773],
 [9.0, 33.6015, 672.03, 33.6015],
 [10.0, 20.825, 416.5, 20.825],
 [9.0, 22.068, 441.36, 22.068],
 [9.0, 9.0045, 180.09, 9.0045],
 [10.0, 39.155, 783.1, 39.155],
 [5.0, 5.095, 101.9, 5.095],
 [6.0, 29.757, 595.14, 29.757],
 [3.0, 14.502, 290.04, 14.502],
 [8.0, 7.7, 154.0, 7.7],
 [4.0, 16.072, 321.44, 16.072],
 [5.0, 12.2275, 244.55, 12.2275],
 [7.0, 29.071, 581.42, 29.071],
 [5.0, 19.13, 382.6, 19.13],
 [7.0, 17.283, 345.66, 17.283],
 [1.0, 2.1235, 42.47, 2.1235],
 [6.0, 23.097, 461.94, 23.097],
 [4.0, 9.476, 189.52, 9.476],
 [10.0, 22.43, 448.6, 22.43],
 [7.0, 7.693, 153.86, 7.693],
 [9.0, 28.962, 579.24, 28.962],
 [1.0, 4.4875, 89.75, 4.4875],
 [1.0, 4.858, 97.16, 4.858],
 [10.0, 43.935, 878.7, 43.935],
 [6.0, 3.735, 74.7, 3.735],
 [3.0, 7.9125, 158.25, 7.9125],
 [6.0, 24.81, 496.2, 24.81],
 [1.0, 2.4355, 48.71, 2.4355],
 [9.0, 35.3475, 706.95, 35.3475],
 [9.0, 10.3815, 207.63, 10.3815],
 [6.0, 17.478, 349.56, 17.478],
 [7.0, 10.6225, 212.45, 10.6225],
 [10.0, 44.335, 886.7, 44.335],
 [6.0, 8.214, 164.28, 8.214],
 [6.0, 18.639, 372.78, 18.639],
 [9.0, 15.291, 305.82, 15.291],
 [10.0, 40.985, 819.7, 40.985],
 [2.0, 1.649, 32.98, 1.649],
 [3.0, 14.7315, 294.63, 14.7315],
 [7.0, 25.494, 509.88, 25.494],
 [9.0, 26.1315, 522.63, 26.1315],
 [9.0, 36.3555, 727.11, 36.3555],
 [3.0, 4.053, 81.06, 4.053],
 [5.0, 5.485, 109.7, 5.485],
 [1.0, 2.568, 51.36, 2.568],
 [10.0, 5.48, 109.6, 5.48],
 [2.0, 5.344, 106.88, 5.344],
 [8.0, 39.824, 796.48, 39.824],
 [7.0, 19.992, 399.84, 19.992],
 [9.0, 44.982, 899.64, 44.982],
 [8.0, 25.564, 511.28, 25.564],
 [8.0, 22.588, 451.76, 22.588],
 [7.0, 32.7915, 655.83, 32.7915],
 [5.0, 8.0625, 161.25, 8.0625],
 [9.0, 14.2785, 285.57, 14.2785],
 [8.0, 27.416, 548.32, 27.416],
 [9.0, 40.626, 812.52, 40.626],
 [7.0, 13.867, 277.34, 13.867],
 [6.0, 27.639, 552.78, 27.639],
 [4.0, 6.968, 139.36, 6.968],
 [6.0, 26.235, 524.7, 26.235],
 [6.0, 24.39, 487.8, 24.39],
 [3.0, 13.533, 270.66, 13.533],
 [5.0, 6.5775, 131.55, 6.5775],
 [6.0, 10.326, 206.52, 10.326],
 [10.0, 25.955, 519.1, 25.955],
 [8.0, 29.0, 580.0, 29.0],
 [10.0, 44.9, 898.0, 44.9],
 [10.0, 45.25, 905.0, 45.25],
 [10.0, 34.3, 686.0, 34.3],
 [1.0, 1.5205, 30.41, 1.5205],
 [6.0, 23.385, 467.7, 23.385],
 [6.0, 13.878, 277.56, 13.878],
 [10.0, 15.07, 301.4, 15.07],
 [4.0, 13.228, 264.56, 13.228],
 [8.0, 28.744, 574.88, 28.744],
 [8.0, 12.984, 259.68, 12.984],
 [4.0, 18.308, 366.16, 18.308],
 [7.0, 12.096, 241.92, 12.096],
 [9.0, 37.458, 749.16, 37.458],
 [6.0, 4.944, 98.88, 4.944],
 [8.0, 32.388, 647.76, 32.388],
 [5.0, 23.0725, 461.45, 23.0725],
 [1.0, 3.6085, 72.17, 3.6085],
 [5.0, 12.57, 251.4, 12.57],
 [9.0, 43.749, 874.98, 43.749],
 [6.0, 28.017, 560.34, 28.017],
 [8.0, 17.272, 345.44, 17.272],
 [1.0, 3.1845, 63.69, 3.1845],
 [7.0, 16.0265, 320.53, 16.0265],
 [2.0, 7.64, 152.8, 7.64],
 [10.0, 19.95, 399.0, 19.95],
 [8.0, 17.028, 340.56, 17.028],
 [10.0, 47.79, 955.8, 47.79],
 [10.0, 49.49, 989.8, 49.49],
 [6.0, 15.384, 307.68, 15.384],
 [7.0, 24.332, 486.64, 24.332],
 [5.0, 17.5025, 350.05, 17.5025],
 [5.0, 20.0125, 400.25, 20.0125],
 [8.0, 8.34, 166.8, 8.34],
 [6.0, 15.867, 317.34, 15.867],
 [8.0, 7.916, 158.32, 7.916],
 [9.0, 15.228, 304.56, 15.228],
 [8.0, 8.868, 177.36, 8.868],
 [7.0, 7.8785, 157.57, 7.8785],
 [6.0, 22.164, 443.28, 22.164],
 [3.0, 13.02, 260.4, 13.02],
 [7.0, 22.491, 449.82, 22.491],
 [8.0, 15.388, 307.76, 15.388],
 [10.0, 7.75, 155.0, 7.75],
 [8.0, 13.724, 274.48, 13.724],
 [7.0, 4.319, 86.38, 4.319],
 [3.0, 2.712, 54.24, 2.712],
 [8.0, 37.796, 755.92, 37.796],
 [4.0, 9.294, 185.88, 9.294],
 [1.0, 3.7035, 74.07, 3.7035],
 [4.0, 13.962, 279.24, 13.962],
 [3.0, 11.556, 231.12, 11.556],
 [2.0, 7.352, 147.04, 7.352],
 [9.0, 39.51, 790.2, 39.51],
 [4.0, 5.11, 102.2, 5.11],
 [5.0, 8.1775, 163.55, 8.1775],
 [1.0, 3.7145, 74.29, 3.7145],
 [2.0, 4.37, 87.4, 4.37],
 [1.0, 1.2645, 25.29, 1.2645],
 [4.0, 8.3, 166.0, 8.3],
 [5.0, 17.8475, 356.95, 17.8475],
 [6.0, 5.745, 114.9, 5.745],
 [4.0, 11.498, 229.96, 11.498],
 [7.0, 21.4935, 429.87, 21.4935],
 [10.0, 12.95, 259.0, 12.95],
 [5.0, 4.4425, 88.85, 4.4425],
 [9.0, 10.3635, 207.27, 10.3635],
 [9.0, 29.9925, 599.85, 29.9925],
 [10.0, 14.265, 285.3, 14.265],
 [3.0, 4.5555, 91.11, 4.5555],
 [9.0, 44.8785, 897.57, 44.8785],
 [9.0, 11.8035, 236.07, 11.8035],
 [9.0, 41.967, 839.34, 41.967],
 [5.0, 23.09, 461.8, 23.09],
 [3.0, 6.963, 139.26, 6.963],
 [7.0, 10.3635, 207.27, 10.3635],
 [1.0, 0.914, 18.28, 0.914],
 [5.0, 6.1925, 123.85, 6.1925],
 [3.0, 14.196, 283.92, 14.196],
 [8.0, 37.948, 758.96, 37.948],
 [3.0, 8.601, 172.02, 8.601],
 [6.0, 13.605, 272.1, 13.605],
 [7.0, 21.728, 434.56, 21.728],
 [5.0, 2.9525, 59.05, 2.9525],
 [1.0, 0.627, 12.54, 0.627],
 [2.0, 4.325, 86.5, 4.325],
 [2.0, 8.716, 174.32, 8.716],
 [9.0, 31.2165, 624.33, 31.2165],
 [4.0, 7.412, 148.24, 7.412],
 [6.0, 27.21, 544.2, 27.21],
 [8.0, 25.368, 507.36, 25.368],
 [2.0, 8.137, 162.74, 8.137],
 [3.0, 1.5885, 31.77, 1.5885],
 [9.0, 37.8405, 756.81, 37.8405],
 [4.0, 14.764, 295.28, 14.764],
 [10.0, 25.97, 519.4, 25.97],
 [2.0, 9.314, 186.28, 9.314],
 [5.0, 4.3525, 87.05, 4.3525],
 [5.0, 11.055, 221.1, 11.055],
 [5.0, 3.305, 66.1, 3.305],
 [1.0, 4.4845, 89.69, 4.4845],
 [9.0, 11.223, 224.46, 11.223],
 [2.0, 5.977, 119.54, 5.977],
 [2.0, 9.32, 186.4, 9.32],
 [4.0, 12.53, 250.6, 12.53],
 [8.0, 37.548, 750.96, 37.548],
 [8.0, 19.036, 380.72, 19.036],
 [3.0, 12.21, 244.2, 12.21],
 [5.0, 4.485, 89.7, 4.485],
 [4.0, 15.544, 310.88, 15.544],
 [7.0, 25.571, 511.42, 25.571],
 [9.0, 20.9475, 418.95, 20.9475],
 [10.0, 17.595, 351.9, 17.595],
 [2.0, 1.439, 28.78, 1.439],
 [4.0, 4.75, 95.0, 4.75],
 [8.0, 23.56, 471.2, 23.56],
 [4.0, 6.524, 130.48, 6.524],
 [1.0, 3.3175, 66.35, 3.3175],
 [6.0, 7.773, 155.46, 7.773],
 [4.0, 6.45, 129.0, 6.45],
 [4.0, 13.188, 263.76, 13.188],
 [9.0, 33.777, 675.54, 33.777],
 [4.0, 3.29, 65.8, 3.29],
 [4.0, 7.66, 153.2, 7.66],
 [10.0, 11.12, 222.4, 11.12],
 [1.0, 2.7225, 54.45, 2.7225],
 [7.0, 34.44, 688.8, 34.44],
 [4.0, 7.094, 141.88, 7.094],
 [10.0, 37.3, 746.0, 37.3],
 [4.0, 14.148, 282.96, 14.148],
 [10.0, 17.77, 355.4, 17.77],
 [5.0, 16.8575, 337.15, 16.8575],
 [2.0, 2.112, 42.24, 2.112],
 [9.0, 9.693, 193.86, 9.693],
 [2.0, 1.203, 24.06, 1.203],
 [6.0, 29.913, 598.26, 29.913],
 [7.0, 16.7895, 335.79, 16.7895],
 [10.0, 10.91, 218.2, 10.91],
 [4.0, 19.084, 381.68, 19.084],
 [10.0, 35.495, 709.9, 35.495],
 [10.0, 22.01, 440.2, 22.01],
 [8.0, 27.984, 559.68, 27.984],
 [1.0, 1.85, 37.0, 1.85],
 [1.0, 0.767, 15.34, 0.767],
 [6.0, 29.949, 598.98, 29.949],
 [4.0, 9.534, 190.68, 9.534],
 [5.0, 16.67, 333.4, 16.67],
 [1.0, 3.743, 74.86, 3.743],
 [9.0, 10.6875, 213.75, 10.6875],
 [7.0, 16.9785, 339.57, 16.9785],
 [7.0, 33.208, 664.16, 33.208],
 [10.0, 20.15, 403.0, 20.15],
 [7.0, 9.7475, 194.95, 9.7475],
 [1.0, 3.124, 62.48, 3.124],
 [2.0, 3.636, 72.72, 3.636],
 [10.0, 9.055, 181.1, 9.055],
 [5.0, 12.98, 259.6, 12.98],
 [4.0, 5.768, 115.36, 5.768],
 [6.0, 23.514, 470.28, 23.514],
 [4.0, 12.002, 240.04, 12.002],
 [1.0, 4.4305, 88.61, 4.4305],
 [2.0, 9.982, 199.64, 9.982],
 [1.0, 1.9505, 39.01, 1.9505],
 [1.0, 2.4305, 48.61, 2.4305],
 [4.0, 10.238, 204.76, 10.238],
 [8.0, 5.984, 119.68, 5.984],
 [7.0, 25.27, 505.4, 25.27],
 [7.0, 14.0805, 281.61, 14.0805],
 [8.0, 35.516, 710.32, 35.516],
 [3.0, 3.972, 79.44, 3.972],
 [2.0, 8.191, 163.82, 8.191],
 [6.0, 23.979, 479.58, 23.979],
 [2.0, 6.933, 138.66, 6.933],
 [5.0, 3.5575, 71.15, 3.5575],
 [9.0, 6.9975, 139.95, 6.9975],
 [10.0, 39.065, 781.3, 39.065],
 [2.0, 9.937, 198.74, 9.937],
 [3.0, 3.162, 63.24, 3.162],
 [5.0, 18.6975, 373.95, 18.6975],
 [7.0, 10.3845, 207.69, 10.3845],
 [4.0, 8.814, 176.28, 8.814],
 [9.0, 10.3185, 206.37, 10.3185],
 [1.0, 1.971, 39.42, 1.971],
 [6.0, 4.578, 91.56, 4.578],
 [5.0, 15.4425, 308.85, 15.4425],
 [6.0, 6.456, 129.12, 6.456],
 [4.0, 19.548, 390.96, 19.548],
 [5.0, 24.945, 498.9, 24.945],
 [4.0, 18.852, 377.04, 18.852],
 [4.0, 10.226, 204.52, 10.226],
 [4.0, 7.272, 145.44, 7.272],
 [9.0, 9.909, 198.18, 9.909],
 [3.0, 4.935, 98.7, 4.935],
 [5.0, 19.255, 385.1, 19.255],
 [2.0, 2.348, 46.96, 2.348],
 [5.0, 3.675, 73.5, 3.675],
 [5.0, 7.1125, 142.25, 7.1125],
 [9.0, 34.38, 687.6, 34.38],
 [6.0, 17.385, 347.7, 17.385],
 [3.0, 7.1475, 142.95, 7.1475],
 [9.0, 19.269, 385.38, 19.269],
 [3.0, 7.2135, 144.27, 7.2135],
 [7.0, 19.5895, 391.79, 19.5895],
 [7.0, 26.915, 538.3, 26.915],
 [5.0, 24.2575, 485.15, 24.2575],
 [3.0, 6.6975, 133.95, 6.6975],
 [9.0, 35.0685, 701.37, 35.0685],
 [1.0, 3.5975, 71.95, 3.5975],
 [8.0, 35.7, 714.0, 35.7],
 [7.0, 9.107, 182.14, 9.107],
 [10.0, 6.75, 135.0, 6.75],
 [10.0, 49.65, 993.0, 49.65],
 [7.0, 18.0915, 361.83, 18.0915],
 [7.0, 19.1555, 383.11, 19.1555],
 [9.0, 12.15, 243.0, 12.15],
 [1.0, 1.512, 30.24, 1.512],
 [4.0, 17.828, 356.56, 17.828],
 [10.0, 18.775, 375.5, 18.775],
 [10.0, 47.72, 954.4, 47.72],
 [3.0, 4.125, 82.5, 4.125],
 [1.0, 3.7485, 74.97, 3.7485],
 [8.0, 32.384, 647.68, 32.384],
 [8.0, 37.788, 755.76, 37.788],
 [2.0, 9.979, 199.58, 9.979],
 [6.0, 21.966, 439.32, 21.966],
 [4.0, 8.248, 164.96, 8.248],
 [4.0, 16.336, 326.72, 16.336],
 [9.0, 23.094, 461.88, 23.094],
 [4.0, 13.188, 263.76, 13.188],
 [10.0, 7.18, 143.6, 7.18],
 [9.0, 9.675, 193.5, 9.675],
 [7.0, 9.191, 183.82, 9.191],
 [2.0, 6.096, 121.92, 6.096],
 [6.0, 21.033, 420.66, 21.033],
 [6.0, 12.624, 252.48, 12.624],
 [5.0, 16.7725, 335.45, 16.7725],
 [5.0, 24.175, 483.5, 24.175],
 [9.0, 15.921, 318.42, 15.921],
 [7.0, 33.4215, 668.43, 33.4215],
 [4.0, 19.396, 387.92, 19.396],
 [4.0, 4.73, 94.6, 4.73],
 [4.0, 16.466, 329.32, 16.466],
 [2.0, 2.661, 53.22, 2.661],
 [5.0, 24.9225, 498.45, 24.9225],
 [4.0, 14.978, 299.56, 14.978],
 [5.0, 10.235, 204.7, 10.235],
 [1.0, 3.791, 75.82, 3.791],
 [6.0, 14.031, 280.62, 14.031],
 [10.0, 16.16, 323.2, 16.16],
 [9.0, 24.3315, 486.63, 24.3315],
 [7.0, 6.377, 127.54, 6.377],
 [3.0, 12.072, 241.44, 12.072],
 [10.0, 18.975, 379.5, 18.975],
 [1.0, 3.841, 76.82, 3.841],
 [10.0, 26.13, 522.6, 26.13],
 [1.0, 3.987, 79.74, 3.987],
 [5.0, 19.375, 387.5, 19.375],
 [5.0, 13.5675, 271.35, 13.5675],
 [9.0, 6.1155, 122.31, 6.1155],
 [6.0, 12.318, 246.36, 12.318],
 [9.0, 8.658, 173.16, 8.658],
 [6.0, 11.829, 236.58, 11.829],
 [4.0, 9.244, 184.88, 9.244],
 [1.0, 0.699, 13.98, 0.699],
 [5.0, 9.9375, 198.75, 9.9375],
 [7.0, 34.2265, 684.53, 34.2265],
 [4.0, 13.452, 269.04, 13.452],
 [5.0, 3.4475, 68.95, 3.4475],
 [4.0, 13.742, 274.84, 13.742],
 [4.0, 11.306, 226.12, 11.306],
 [5.0, 5.955, 119.1, 5.955],
 [10.0, 17.105, 342.1, 17.105],
 [2.0, 2.187, 43.74, 2.187],
 [5.0, 5.2425, 104.85, 5.2425],
 [3.0, 3.876, 77.52, 3.876],
 [8.0, 20.372, 407.44, 20.372],
 [1.0, 4.8055, 96.11, 4.8055],
 [4.0, 9.076, 181.52, 9.076],
 [1.0, 4.0755, 81.51, 4.0755],
 [2.0, 5.722, 114.44, 5.722],
 [7.0, 8.827, 176.54, 8.827],
 [3.0, 5.79, 115.8, 5.79],
 [3.0, 12.6075, 252.15, 12.6075],
 [10.0, 48.605, 972.1, 48.605],
 [8.0, 10.168, 203.36, 10.168],
 [1.0, 0.814, 16.28, 0.814],
 [9.0, 18.2745, 365.49, 18.2745],
 [7.0, 18.6095, 372.19, 18.6095],
 [3.0, 3.1305, 62.61, 3.1305],
 [5.0, 16.8175, 336.35, 16.8175],
 [10.0, 45.325, 906.5, 45.325],
 [2.0, 6.908, 138.16, 6.908],
 [2.0, 4.327, 86.54, 4.327],
 [6.0, 7.038, 140.76, 7.038],
 [7.0, 33.439, 668.78, 33.439],
 [1.0, 2.372, 47.44, 2.372],
 [9.0, 44.658, 893.16, 44.658],
 [4.0, 16.586, 331.72, 16.586],
 [6.0, 10.197, 203.94, 10.197],
 [4.0, 3.408, 68.16, 3.408],
 [8.0, 16.344, 326.88, 16.344],
 [5.0, 4.36, 87.2, 4.36],
 [8.0, 35.372, 707.44, 35.372],
 [9.0, 40.1445, 802.89, 40.1445],
 [1.0, 0.639, 12.78, 0.639],
 [7.0, 6.685, 133.7, 6.685],
 [1.0, 0.9575, 19.15, 0.9575],
 [10.0, 13.83, 276.6, 13.83],
 [3.0, 6.861, 137.22, 6.861],
 [1.0, 1.3535, 27.07, 1.3535],
 [1.0, 1.956, 39.12, 1.956],
 [6.0, 22.413, 448.26, 22.413],
 [6.0, 6.603, 132.06, 6.603],
 [5.0, 15.9025, 318.05, 15.9025],
 [1.0, 1.25, 25.0, 1.25],
 [4.0, 4.154, 83.08, 4.154],
 [5.0, 7.39, 147.8, 7.39],
 [9.0, 34.83, 696.6, 34.83],
 [10.0, 39.695, 793.9, 39.695],
 [10.0, 23.285, 465.7, 23.285],
 [1.0, 1.7945, 35.89, 1.7945],
 [5.0, 10.13, 202.6, 10.13],
 [10.0, 36.525, 730.5, 36.525],
 [4.0, 14.79, 295.8, 14.79],
 [1.0, 1.131, 22.62, 1.131],
 [5.0, 12.835, 256.7, 12.835],
 [10.0, 27.275, 545.5, 27.275],
 [7.0, 13.0025, 260.05, 13.0025],
 [6.0, 11.106, 222.12, 11.106],
 [1.0, 1.079, 21.58, 1.079],
 [1.0, 4.942, 98.84, 4.942],
 [6.0, 25.131, 502.62, 25.131],
 [4.0, 8.01, 160.2, 8.01],
 [10.0, 21.565, 431.3, 21.565],
 [8.0, 29.028, 580.56, 29.028],
 [5.0, 16.11, 322.2, 16.11],
 [3.0, 9.777, 195.54, 9.777],
 [5.0, 8.315, 166.3, 8.315],
 [4.0, 16.814, 336.28, 16.814],
 [10.0, 17.185, 343.7, 17.185],
 [1.0, 1.93, 38.6, 1.93],
 [8.0, 26.388, 527.76, 26.388],
 [10.0, 16.4, 328.0, 16.4],
 [5.0, 9.285, 185.7, 9.285],
 [10.0, 30.19, 603.8, 30.19],
 [10.0, 18.49, 369.8, 18.49],
 [4.0, 9.898, 197.96, 9.898],
 [10.0, 20.545, 410.9, 20.545],
 [4.0, 7.43, 148.6, 7.43],
 [1.0, 1.148, 22.96, 1.148],
 [9.0, 34.956, 699.12, 34.956],
 [2.0, 3.47, 69.4, 3.47],
 [10.0, 9.83, 196.6, 9.83],
 [8.0, 10.128, 202.56, 10.128],
 [10.0, 6.06, 121.2, 6.06],
 [2.0, 9.989, 199.78, 9.989],
 [8.0, 30.368, 607.36, 30.368],
 [2.0, 6.322, 126.44, 6.322],
 [6.0, 27.072, 541.44, 27.072],
 [1.0, 4.9065, 98.13, 4.9065],
 [8.0, 20.608, 412.16, 20.608],
 [1.0, 3.6985, 73.97, 3.6985],
 [1.0, 1.595, 31.9, 1.595],
 [2.0, 6.94, 138.8, 6.94],
 [2.0, 9.331, 186.62, 9.331],
 [1.0, 4.4225, 88.45, 4.4225],
 [8.0, 9.672, 193.44, 9.672],
 [3.0, 7.275, 145.5, 7.275],
 [6.0, 25.215, 504.3, 25.215],
 [5.0, 15.3225, 306.45, 15.3225],
 [6.0, 4.785, 95.7, 4.785],
 [7.0, 31.759, 635.18, 31.759],
 [5.0, 10.7275, 214.55, 10.7275],
 [7.0, 18.998, 379.96, 18.998],
 [7.0, 34.8425, 696.85, 34.8425],
 [7.0, 20.4365, 408.73, 20.4365],
 [1.0, 2.5735, 51.47, 2.5735],
 [5.0, 13.715, 274.3, 13.715],
 [5.0, 9.8475, 196.95, 9.8475],
 [2.0, 3.473, 69.46, 3.473],
 [5.0, 17.98, 359.6, 17.98],
 [3.0, 6.8565, 137.13, 6.8565],
 [6.0, 24.951, 499.02, 24.951],
 [6.0, 11.232, 224.64, 11.232],
 [2.0, 6.287, 125.74, 6.287],
 [6.0, 24.513, 490.26, 24.513],
 [5.0, 22.8525, 457.05, 22.8525],
 [4.0, 7.842, 156.84, 7.842],
 [2.0, 5.986, 119.72, 5.986],
 [10.0, 27.18, 543.6, 27.18],
 [9.0, 44.1405, 882.81, 44.1405],
 [6.0, 7.629, 152.58, 7.629],
 [8.0, 34.672, 693.44, 34.672],
 [10.0, 11.475, 229.5, 11.475],
 [9.0, 7.3395, 146.79, 7.3395],
 [5.0, 7.08, 141.6, 7.08],
 [7.0, 5.8345, 116.69, 5.8345],
 [1.0, 3.698, 73.96, 3.698],
 [1.0, 4.897, 97.94, 4.897],
 [4.0, 14.61, 292.2, 14.61],
 [6.0, 26.244, 524.88, 26.244],
 [3.0, 4.602, 92.04, 4.602],
 [1.0, 3.794, 75.88, 3.794],
 [4.0, 4.036, 80.72, 4.036],
 [6.0, 5.631, 112.62, 5.631],
 [1.0, 3.56, 71.2, 3.56],
 [4.0, 7.762, 155.24, 7.762],
 [10.0, 14.71, 294.2, 14.71],
 [9.0, 27.4275, 548.55, 27.4275],
 [5.0, 12.885, 257.7, 12.885],
 [6.0, 19.818, 396.36, 19.818],
 [3.0, 8.5905, 171.81, 8.5905],
 [9.0, 24.4395, 488.79, 24.4395],
 [9.0, 26.208, 524.16, 26.208],
 [6.0, 6.663, 133.26, 6.663],
 [7.0, 6.762, 135.24, 6.762],
 [3.0, 5.622, 112.44, 5.622],
 [2.0, 7.204, 144.08, 7.204],
 [10.0, 49.26, 985.2, 49.26],
 [6.0, 12.498, 249.96, 12.498],
 [3.0, 10.863, 217.26, 10.863],
 [9.0, 9.711, 194.22, 9.711],
 [10.0, 44.6, 892.0, 44.6],
 [8.0, 16.968, 339.36, 16.968],
 [6.0, 22.353, 447.06, 22.353],
 [2.0, 9.925, 198.5, 9.925],
 [10.0, 40.605, 812.1, 40.605],
 [10.0, 24.665, 493.3, 24.665],
 [9.0, 29.583, 591.66, 29.583],
 [7.0, 27.951, 559.02, 27.951],
 [7.0, 25.893, 517.86, 25.893],
 [5.0, 20.51, 410.2, 20.51],
 [10.0, 13.335, 266.7, 13.335],
 [7.0, 3.5455, 70.91, 3.5455],
 [2.0, 7.239, 144.78, 7.239],
 [5.0, 21.4775, 429.55, 21.4775],
 [7.0, 28.4585, 569.17, 28.4585],
 [4.0, 12.06, 241.2, 12.06],
 [4.0, 6.354, 127.08, 6.354],
 [4.0, 12.854, 257.08, 12.854],
 [2.0, 6.951, 139.02, 6.951],
 [3.0, 4.083, 81.66, 4.083],
 [4.0, 15.536, 310.72, 15.536],
 [2.0, 9.298, 185.96, 9.298],
 [4.0, 3.616, 72.32, 3.616],
 [3.0, 9.459, 189.18, 9.459],
 [4.0, 10.342, 206.84, 10.342],
 [3.0, 7.851, 157.02, 7.851],
 [5.0, 10.765, 215.3, 10.765],
 [10.0, 29.805, 596.1, 29.805],
 [5.0, 3.655, 73.1, 3.655],
 [6.0, 13.959, 279.18, 13.959],
 [7.0, 8.484, 169.68, 8.484],
 [1.0, 2.279, 45.58, 2.279],
 [3.0, 11.28, 225.6, 11.28],
 [3.0, 14.52, 290.4, 14.52],
 [3.0, 2.223, 44.46, 2.223],
 [3.0, 7.83, 156.6, 7.83],
 [9.0, 20.997, 419.94, 20.997],
 [5.0, 9.2125, 184.25, 9.2125],
 [2.0, 7.032, 140.64, 7.032],
 [1.0, 4.154, 83.08, 4.154],
 [1.0, 3.2495, 64.99, 3.2495],
 [10.0, 38.78, 775.6, 38.78],
 [6.0, 16.353, 327.06, 16.353],
 [7.0, 18.1615, 363.23, 18.1615],
 [4.0, 6.35, 127.0, 6.35],
 [7.0, 18.7775, 375.55, 18.7775],
 [4.0, 9.958, 199.16, 9.958],
 [1.0, 1.5305, 30.61, 1.5305],
 [2.0, 5.789, 115.78, 5.789],
 [1.0, 1.448, 28.96, 1.448],
 [9.0, 44.5365, 890.73, 44.5365],
 [3.0, 13.983, 279.66, 13.983],
 [1.0, 4.0465, 80.93, 4.0465],
 [10.0, 33.725, 674.5, 33.725],
 [9.0, 17.424, 348.48, 17.424],
 [6.0, 21.78, 435.6, 21.78],
 [5.0, 21.9775, 439.55, 21.9775],
 [6.0, 29.559, 591.18, 29.559],
 [6.0, 13.038, 260.76, 13.038],
 [3.0, 10.752, 215.04, 10.752],
 [1.0, 4.5805, 91.61, 4.5805],
 [7.0, 33.1065, 662.13, 33.1065],
 [10.0, 41.625, 832.5, 41.625],
 [1.0, 4.5675, 91.35, 4.5675],
 [2.0, 7.888, 157.76, 7.888],
 [2.0, 6.087, 121.74, 6.087],
 [10.0, 41.29, 825.8, 41.29],
 [3.0, 7.995, 159.9, 7.995],
 [1.0, 0.6045, 12.09, 0.6045],
 [10.0, 32.095, 641.9, 32.095],
 [3.0, 11.7465, 234.93, 11.7465],
 [2.0, 8.377, 167.54, 8.377],
 [3.0, 14.955, 299.1, 14.955],
 [3.0, 11.9865, 239.73, 11.9865],
 [10.0, 33.235, 664.7, 33.235],
 [7.0, 10.1325, 202.65, 10.1325],
 [1.0, 2.31, 46.2, 2.31],
 [5.0, 4.4075, 88.15, 4.4075],
 [3.0, 7.863, 157.26, 7.863],
 [3.0, 14.8185, 296.37, 14.8185],
 [8.0, 35.42, 708.4, 35.42],
 [2.0, 5.567, 111.34, 5.567],
 [8.0, 29.008, 580.16, 29.008],
 [5.0, 3.0125, 60.25, 3.0125],
 [9.0, 8.712, 174.24, 8.712],
 [6.0, 21.063, 421.26, 21.063],

In [ ]:
quantity_input=float(input("Quantity:"))
vat_input=float(input("Vat:"))
cogs_input=float(input("Cost of goods sold:"))